### PR TITLE
Add french translation and chat message translation

### PR DESCRIPTION
**Pull request by Kirwiisp**
I wanted to add a french translation, i extended it with the translation of chat messages without the need to translate the db. 
The inconvenience is a bigger fr.json.

- add fr.json
- add missing localize on templates 
- add chat message translation for mythic gme 2

### CODE REVIEW

**Comment by saif-ellafi** [comment]
WOW! @Kirwiisp - this is BIG. And I didn't know you could translate any strings! This will require to extend these word translation in the other languages too so all can benefit from this using yours as a template :)

Would this also translate table content?

**Comment by Kirwiisp** [comment]
I think if the others tables use a similar entry it should be translated. 
I haven't translated the entries for the others tables cause i'm still not used to use api to automatise the translation (still used regex and copy paste 😅)
I can easily edit the english en.json to add the new entries

**Comment by Kirwiisp** [comment]
Translations added to every lang files. It's just simple google traduction, it might certainly need some fine tuning form natives, but it's a first access and should work for everyone

**Comment by saif-ellafi** [comment]
Brilliant!! Will test soon and release

**Pull request merged**
